/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* src = "ackor.v:4" *)
module ackor(ack0x, ack1x, ack2x, ack3x, ack);
  wire _0_;
  wire _1_;
  (* src = "ackor.v:4" *)
  output ack;
  (* src = "ackor.v:4" *)
  input ack0x;
  (* src = "ackor.v:4" *)
  input ack1x;
  (* src = "ackor.v:4" *)
  input ack2x;
  (* src = "ackor.v:4" *)
  input ack3x;
  assign _0_ = ack1x | ack0x;
  assign _1_ = _0_ | ack2x;
  assign ack = _1_ | ack3x;
endmodule

(* src = "arb.v:4" *)
module arb(req0, req1, req2, req3, ackx0, ackx1, ackx2, ackx3, clk, rst);
  (* src = "arb.v:17" *)
  wire _00_;
  (* src = "arb.v:17" *)
  wire _01_;
  (* src = "arb.v:17" *)
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "arb.v:4" *)
  output ackx0;
  reg ackx0;
  (* src = "arb.v:4" *)
  output ackx1;
  reg ackx1;
  (* src = "arb.v:4" *)
  output ackx2;
  reg ackx2;
  (* src = "arb.v:4" *)
  output ackx3;
  reg ackx3;
  (* src = "arb.v:4" *)
  input clk;
  (* src = "arb.v:4" *)
  input req0;
  (* src = "arb.v:4" *)
  input req1;
  (* src = "arb.v:4" *)
  input req2;
  (* src = "arb.v:4" *)
  input req3;
  (* src = "arb.v:4" *)
  input rst;
  (* src = "arb.v:14" *)
  wire turn;
  assign _04_ = req2 | ~(req3);
  assign _05_ = _04_ | req1;
  assign _02_ = ~(_05_ | req0);
  assign _03_ = req1 | ~(req2);
  assign _01_ = ~(_03_ | req0);
  assign _00_ = req1 & ~(req0);
  (* src = "arb.v:17" *)
  always @(posedge clk)
      ackx0 <= req0;
  (* src = "arb.v:17" *)
  always @(posedge clk)
      ackx1 <= _00_;
  (* src = "arb.v:17" *)
  always @(posedge clk)
      ackx2 <= _01_;
  (* src = "arb.v:17" *)
  always @(posedge clk)
      ackx3 <= _02_;
  assign turn = 1'h0;
endmodule

(* src = "cb.v:4" *)
module cb(i0, i1, i2, i3, o0, o1, o2, o3, d0, d1, d2, d3);
  (* src = "cb.v:5" *)
  input [3:0] d0;
  (* src = "cb.v:5" *)
  input [3:0] d1;
  (* src = "cb.v:5" *)
  input [3:0] d2;
  (* src = "cb.v:5" *)
  input [3:0] d3;
  (* src = "cb.v:4" *)
  input [9:0] i0;
  (* src = "cb.v:4" *)
  input [9:0] i1;
  (* src = "cb.v:4" *)
  input [9:0] i2;
  (* src = "cb.v:4" *)
  input [9:0] i3;
  (* src = "cb.v:4" *)
  output [9:0] o0;
  (* src = "cb.v:4" *)
  output [9:0] o1;
  (* src = "cb.v:4" *)
  output [9:0] o2;
  (* src = "cb.v:4" *)
  output [9:0] o3;
  (* module_not_derived = 32'd1 *)
  (* src = "cb.v:12" *)
  cbsel cbsel0 (
    .d(d0),
    .i0(i0),
    .i1(i1),
    .i2(i2),
    .i3(i3),
    .o(o0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cb.v:13" *)
  cbsel cbsel1 (
    .d(d1),
    .i0(i0),
    .i1(i1),
    .i2(i2),
    .i3(i3),
    .o(o1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cb.v:14" *)
  cbsel cbsel2 (
    .d(d2),
    .i0(i0),
    .i1(i1),
    .i2(i2),
    .i3(i3),
    .o(o2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cb.v:15" *)
  cbsel cbsel3 (
    .d(d3),
    .i0(i0),
    .i1(i1),
    .i2(i2),
    .i3(i3),
    .o(o3)
  );
endmodule

(* src = "cbsel.v:4" *)
module cbsel(i0, i1, i2, i3, o, d);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  (* src = "cbsel.v:4" *)
  input [3:0] d;
  (* src = "cbsel.v:4" *)
  input [9:0] i0;
  (* src = "cbsel.v:4" *)
  input [9:0] i1;
  (* src = "cbsel.v:4" *)
  input [9:0] i2;
  (* src = "cbsel.v:4" *)
  input [9:0] i3;
  (* src = "cbsel.v:4" *)
  output [9:0] o;
  assign _00_ = d[3] & i3[0];
  assign _01_ = d[2] ? i2[0] : _00_;
  assign _02_ = d[1] ? i1[0] : _01_;
  assign o[0] = d[0] ? i0[0] : _02_;
  assign _03_ = i3[1] & d[3];
  assign _04_ = d[2] ? i2[1] : _03_;
  assign _05_ = d[1] ? i1[1] : _04_;
  assign o[1] = d[0] ? i0[1] : _05_;
  assign _06_ = i3[2] & d[3];
  assign _07_ = d[2] ? i2[2] : _06_;
  assign _08_ = d[1] ? i1[2] : _07_;
  assign o[2] = d[0] ? i0[2] : _08_;
  assign _09_ = i3[3] & d[3];
  assign _10_ = d[2] ? i2[3] : _09_;
  assign _11_ = d[1] ? i1[3] : _10_;
  assign o[3] = d[0] ? i0[3] : _11_;
  assign _12_ = i3[4] & d[3];
  assign _13_ = d[2] ? i2[4] : _12_;
  assign _14_ = d[1] ? i1[4] : _13_;
  assign o[4] = d[0] ? i0[4] : _14_;
  assign _15_ = i3[5] & d[3];
  assign _16_ = d[2] ? i2[5] : _15_;
  assign _17_ = d[1] ? i1[5] : _16_;
  assign o[5] = d[0] ? i0[5] : _17_;
  assign _18_ = i3[6] & d[3];
  assign _19_ = d[2] ? i2[6] : _18_;
  assign _20_ = d[1] ? i1[6] : _19_;
  assign o[6] = d[0] ? i0[6] : _20_;
  assign _21_ = i3[7] & d[3];
  assign _22_ = d[2] ? i2[7] : _21_;
  assign _23_ = d[1] ? i1[7] : _22_;
  assign o[7] = d[0] ? i0[7] : _23_;
  assign _24_ = i3[8] & d[3];
  assign _25_ = d[2] ? i2[8] : _24_;
  assign _26_ = d[1] ? i1[8] : _25_;
  assign o[8] = d[0] ? i0[8] : _26_;
  assign _27_ = i3[9] & d[3];
  assign _28_ = d[2] ? i2[9] : _27_;
  assign _29_ = d[1] ? i1[9] : _28_;
  assign o[9] = d[0] ? i0[9] : _29_;
endmodule

(* src = "fifo.v:4" *)
module fifo(in, we, full, out, re, empty, clk, rst);
  (* src = "fifo.v:13" *)
  wire [3:0] _000_;
  (* src = "fifo.v:13" *)
  wire [3:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  (* src = "fifo.v:5" *)
  input clk;
  (* src = "fifo.v:5" *)
  output empty;
  (* src = "fifo.v:4" *)
  output full;
  (* src = "fifo.v:6" *)
  reg [3:0] head;
  (* src = "fifo.v:4" *)
  input [9:0] in;
  reg [9:0] \mem[0] ;
  reg [9:0] \mem[10] ;
  reg [9:0] \mem[11] ;
  reg [9:0] \mem[12] ;
  reg [9:0] \mem[13] ;
  reg [9:0] \mem[14] ;
  reg [9:0] \mem[15] ;
  reg [9:0] \mem[1] ;
  reg [9:0] \mem[2] ;
  reg [9:0] \mem[3] ;
  reg [9:0] \mem[4] ;
  reg [9:0] \mem[5] ;
  reg [9:0] \mem[6] ;
  reg [9:0] \mem[7] ;
  reg [9:0] \mem[8] ;
  reg [9:0] \mem[9] ;
  (* src = "fifo.v:5" *)
  output [9:0] out;
  (* src = "fifo.v:5" *)
  input re;
  (* src = "fifo.v:5" *)
  input rst;
  (* src = "fifo.v:6" *)
  reg [3:0] tail;
  (* src = "fifo.v:4" *)
  input we;
  assign _162_ = ~(tail[0] ^ head[0]);
  assign _163_ = tail[1] ^ head[1];
  assign _164_ = _163_ | ~(_162_);
  assign _165_ = ~(head[2] ^ tail[2]);
  assign _166_ = tail[3] ^ head[3];
  assign _167_ = _166_ | ~(_165_);
  assign empty = ~(_167_ | _164_);
  assign _168_ = tail[0] ^ head[0];
  assign _169_ = head[0] & ~(head[1]);
  assign _170_ = head[1] & ~(head[0]);
  assign _171_ = ~(_170_ | _169_);
  assign _172_ = ~(_171_ ^ tail[1]);
  assign _173_ = _172_ | ~(_168_);
  assign _174_ = ~tail[2];
  assign _175_ = head[1] & head[0];
  assign _176_ = ~(_175_ ^ head[2]);
  assign _177_ = ~(_176_ ^ _174_);
  assign _178_ = ~head[2];
  assign _179_ = _175_ & ~(_178_);
  assign _180_ = ~(_179_ ^ head[3]);
  assign _181_ = ~(_180_ ^ tail[3]);
  assign _182_ = _181_ | ~(_177_);
  assign full = ~(_182_ | _173_);
  assign _183_ = head[3] | head[2];
  assign _184_ = _183_ | ~(_175_);
  assign _185_ = we & ~(_184_);
  assign _092_ = _185_ ? in[0] : \mem[3] [0];
  assign _093_ = _185_ ? in[1] : \mem[3] [1];
  assign _094_ = _185_ ? in[2] : \mem[3] [2];
  assign _095_ = _185_ ? in[3] : \mem[3] [3];
  assign _096_ = _185_ ? in[4] : \mem[3] [4];
  assign _097_ = _185_ ? in[5] : \mem[3] [5];
  assign _098_ = _185_ ? in[6] : \mem[3] [6];
  assign _099_ = _185_ ? in[7] : \mem[3] [7];
  assign _100_ = _185_ ? in[8] : \mem[3] [8];
  assign _101_ = _185_ ? in[9] : \mem[3] [9];
  assign _186_ = ~(head[1] | head[0]);
  assign _187_ = ~(head[3] & head[2]);
  assign _188_ = _187_ | ~(_186_);
  assign _189_ = _188_ | ~(we);
  assign _032_ = _189_ ? \mem[12] [0] : in[0];
  assign _033_ = _189_ ? \mem[12] [1] : in[1];
  assign _034_ = _189_ ? \mem[12] [2] : in[2];
  assign _035_ = _189_ ? \mem[12] [3] : in[3];
  assign _036_ = _189_ ? \mem[12] [4] : in[4];
  assign _037_ = _189_ ? \mem[12] [5] : in[5];
  assign _038_ = _189_ ? \mem[12] [6] : in[6];
  assign _039_ = _189_ ? \mem[12] [7] : in[7];
  assign _040_ = _189_ ? \mem[12] [8] : in[8];
  assign _041_ = _189_ ? \mem[12] [9] : in[9];
  assign _190_ = head[3] | ~(head[2]);
  assign _191_ = _190_ | ~(_175_);
  assign _192_ = _191_ | ~(we);
  assign _132_ = _192_ ? \mem[7] [0] : in[0];
  assign _133_ = _192_ ? \mem[7] [1] : in[1];
  assign _134_ = _192_ ? \mem[7] [2] : in[2];
  assign _135_ = _192_ ? \mem[7] [3] : in[3];
  assign _136_ = _192_ ? \mem[7] [4] : in[4];
  assign _137_ = _192_ ? \mem[7] [5] : in[5];
  assign _138_ = _192_ ? \mem[7] [6] : in[6];
  assign _139_ = _192_ ? \mem[7] [7] : in[7];
  assign _140_ = _192_ ? \mem[7] [8] : in[8];
  assign _141_ = _192_ ? \mem[7] [9] : in[9];
  assign _193_ = _190_ | ~(_186_);
  assign _194_ = _193_ | ~(we);
  assign _102_ = _194_ ? \mem[4] [0] : in[0];
  assign _103_ = _194_ ? \mem[4] [1] : in[1];
  assign _104_ = _194_ ? \mem[4] [2] : in[2];
  assign _105_ = _194_ ? \mem[4] [3] : in[3];
  assign _106_ = _194_ ? \mem[4] [4] : in[4];
  assign _107_ = _194_ ? \mem[4] [5] : in[5];
  assign _108_ = _194_ ? \mem[4] [6] : in[6];
  assign _109_ = _194_ ? \mem[4] [7] : in[7];
  assign _110_ = _194_ ? \mem[4] [8] : in[8];
  assign _111_ = _194_ ? \mem[4] [9] : in[9];
  assign _195_ = tail[0] ? \mem[1] [0] : \mem[0] [0];
  assign _196_ = tail[0] ? \mem[3] [0] : \mem[2] [0];
  assign _197_ = tail[1] ? _196_ : _195_;
  assign _198_ = tail[0] ? \mem[5] [0] : \mem[4] [0];
  assign _199_ = tail[0] ? \mem[7] [0] : \mem[6] [0];
  assign _200_ = tail[1] ? _199_ : _198_;
  assign _201_ = tail[2] ? _200_ : _197_;
  assign _202_ = tail[0] ? \mem[9] [0] : \mem[8] [0];
  assign _203_ = tail[0] ? \mem[11] [0] : \mem[10] [0];
  assign _204_ = tail[1] ? _203_ : _202_;
  assign _205_ = tail[0] ? \mem[13] [0] : \mem[12] [0];
  assign _206_ = tail[0] ? \mem[15] [0] : \mem[14] [0];
  assign _207_ = tail[1] ? _206_ : _205_;
  assign _208_ = tail[2] ? _207_ : _204_;
  assign _209_ = tail[3] ? _208_ : _201_;
  assign out[0] = _209_ & ~(empty);
  assign _210_ = tail[0] ? \mem[1] [1] : \mem[0] [1];
  assign _211_ = tail[0] ? \mem[3] [1] : \mem[2] [1];
  assign _212_ = tail[1] ? _211_ : _210_;
  assign _213_ = tail[0] ? \mem[5] [1] : \mem[4] [1];
  assign _214_ = tail[0] ? \mem[7] [1] : \mem[6] [1];
  assign _215_ = tail[1] ? _214_ : _213_;
  assign _216_ = tail[2] ? _215_ : _212_;
  assign _217_ = tail[0] ? \mem[9] [1] : \mem[8] [1];
  assign _218_ = tail[0] ? \mem[11] [1] : \mem[10] [1];
  assign _219_ = tail[1] ? _218_ : _217_;
  assign _220_ = tail[0] ? \mem[13] [1] : \mem[12] [1];
  assign _221_ = tail[0] ? \mem[15] [1] : \mem[14] [1];
  assign _222_ = tail[1] ? _221_ : _220_;
  assign _223_ = tail[2] ? _222_ : _219_;
  assign _224_ = tail[3] ? _223_ : _216_;
  assign out[1] = _224_ & ~(empty);
  assign _225_ = tail[0] ? \mem[1] [2] : \mem[0] [2];
  assign _226_ = tail[0] ? \mem[3] [2] : \mem[2] [2];
  assign _227_ = tail[1] ? _226_ : _225_;
  assign _228_ = tail[0] ? \mem[5] [2] : \mem[4] [2];
  assign _229_ = tail[0] ? \mem[7] [2] : \mem[6] [2];
  assign _230_ = tail[1] ? _229_ : _228_;
  assign _231_ = tail[2] ? _230_ : _227_;
  assign _232_ = tail[0] ? \mem[9] [2] : \mem[8] [2];
  assign _233_ = tail[0] ? \mem[11] [2] : \mem[10] [2];
  assign _234_ = tail[1] ? _233_ : _232_;
  assign _235_ = tail[0] ? \mem[13] [2] : \mem[12] [2];
  assign _236_ = tail[0] ? \mem[15] [2] : \mem[14] [2];
  assign _237_ = tail[1] ? _236_ : _235_;
  assign _238_ = tail[2] ? _237_ : _234_;
  assign _239_ = tail[3] ? _238_ : _231_;
  assign out[2] = _239_ & ~(empty);
  assign _240_ = tail[0] ? \mem[1] [3] : \mem[0] [3];
  assign _241_ = tail[0] ? \mem[3] [3] : \mem[2] [3];
  assign _242_ = tail[1] ? _241_ : _240_;
  assign _243_ = tail[0] ? \mem[5] [3] : \mem[4] [3];
  assign _244_ = tail[0] ? \mem[7] [3] : \mem[6] [3];
  assign _245_ = tail[1] ? _244_ : _243_;
  assign _246_ = tail[2] ? _245_ : _242_;
  assign _247_ = tail[0] ? \mem[9] [3] : \mem[8] [3];
  assign _248_ = tail[0] ? \mem[11] [3] : \mem[10] [3];
  assign _249_ = tail[1] ? _248_ : _247_;
  assign _250_ = tail[0] ? \mem[13] [3] : \mem[12] [3];
  assign _251_ = tail[0] ? \mem[15] [3] : \mem[14] [3];
  assign _252_ = tail[1] ? _251_ : _250_;
  assign _253_ = tail[2] ? _252_ : _249_;
  assign _254_ = tail[3] ? _253_ : _246_;
  assign out[3] = _254_ & ~(empty);
  assign _255_ = tail[0] ? \mem[1] [4] : \mem[0] [4];
  assign _256_ = tail[0] ? \mem[3] [4] : \mem[2] [4];
  assign _257_ = tail[1] ? _256_ : _255_;
  assign _258_ = tail[0] ? \mem[5] [4] : \mem[4] [4];
  assign _259_ = tail[0] ? \mem[7] [4] : \mem[6] [4];
  assign _260_ = tail[1] ? _259_ : _258_;
  assign _261_ = tail[2] ? _260_ : _257_;
  assign _262_ = tail[0] ? \mem[9] [4] : \mem[8] [4];
  assign _263_ = tail[0] ? \mem[11] [4] : \mem[10] [4];
  assign _264_ = tail[1] ? _263_ : _262_;
  assign _265_ = tail[0] ? \mem[13] [4] : \mem[12] [4];
  assign _266_ = tail[0] ? \mem[15] [4] : \mem[14] [4];
  assign _267_ = tail[1] ? _266_ : _265_;
  assign _268_ = tail[2] ? _267_ : _264_;
  assign _269_ = tail[3] ? _268_ : _261_;
  assign out[4] = _269_ & ~(empty);
  assign _270_ = tail[0] ? \mem[1] [5] : \mem[0] [5];
  assign _271_ = tail[0] ? \mem[3] [5] : \mem[2] [5];
  assign _272_ = tail[1] ? _271_ : _270_;
  assign _273_ = tail[0] ? \mem[5] [5] : \mem[4] [5];
  assign _274_ = tail[0] ? \mem[7] [5] : \mem[6] [5];
  assign _275_ = tail[1] ? _274_ : _273_;
  assign _276_ = tail[2] ? _275_ : _272_;
  assign _277_ = tail[0] ? \mem[9] [5] : \mem[8] [5];
  assign _278_ = tail[0] ? \mem[11] [5] : \mem[10] [5];
  assign _279_ = tail[1] ? _278_ : _277_;
  assign _280_ = tail[0] ? \mem[13] [5] : \mem[12] [5];
  assign _281_ = tail[0] ? \mem[15] [5] : \mem[14] [5];
  assign _282_ = tail[1] ? _281_ : _280_;
  assign _283_ = tail[2] ? _282_ : _279_;
  assign _284_ = tail[3] ? _283_ : _276_;
  assign out[5] = _284_ & ~(empty);
  assign _285_ = tail[0] ? \mem[1] [6] : \mem[0] [6];
  assign _286_ = tail[0] ? \mem[3] [6] : \mem[2] [6];
  assign _287_ = tail[1] ? _286_ : _285_;
  assign _288_ = tail[0] ? \mem[5] [6] : \mem[4] [6];
  assign _289_ = tail[0] ? \mem[7] [6] : \mem[6] [6];
  assign _290_ = tail[1] ? _289_ : _288_;
  assign _291_ = tail[2] ? _290_ : _287_;
  assign _292_ = tail[0] ? \mem[9] [6] : \mem[8] [6];
  assign _293_ = tail[0] ? \mem[11] [6] : \mem[10] [6];
  assign _294_ = tail[1] ? _293_ : _292_;
  assign _295_ = tail[0] ? \mem[13] [6] : \mem[12] [6];
  assign _296_ = tail[0] ? \mem[15] [6] : \mem[14] [6];
  assign _297_ = tail[1] ? _296_ : _295_;
  assign _298_ = tail[2] ? _297_ : _294_;
  assign _299_ = tail[3] ? _298_ : _291_;
  assign out[6] = _299_ & ~(empty);
  assign _300_ = tail[0] ? \mem[1] [7] : \mem[0] [7];
  assign _301_ = tail[0] ? \mem[3] [7] : \mem[2] [7];
  assign _302_ = tail[1] ? _301_ : _300_;
  assign _303_ = tail[0] ? \mem[5] [7] : \mem[4] [7];
  assign _304_ = tail[0] ? \mem[7] [7] : \mem[6] [7];
  assign _305_ = tail[1] ? _304_ : _303_;
  assign _306_ = tail[2] ? _305_ : _302_;
  assign _307_ = tail[0] ? \mem[9] [7] : \mem[8] [7];
  assign _308_ = tail[0] ? \mem[11] [7] : \mem[10] [7];
  assign _309_ = tail[1] ? _308_ : _307_;
  assign _310_ = tail[0] ? \mem[13] [7] : \mem[12] [7];
  assign _311_ = tail[0] ? \mem[15] [7] : \mem[14] [7];
  assign _312_ = tail[1] ? _311_ : _310_;
  assign _313_ = tail[2] ? _312_ : _309_;
  assign _314_ = tail[3] ? _313_ : _306_;
  assign out[7] = _314_ & ~(empty);
  assign _315_ = tail[0] ? \mem[1] [8] : \mem[0] [8];
  assign _316_ = tail[0] ? \mem[3] [8] : \mem[2] [8];
  assign _317_ = tail[1] ? _316_ : _315_;
  assign _318_ = tail[0] ? \mem[5] [8] : \mem[4] [8];
  assign _319_ = tail[0] ? \mem[7] [8] : \mem[6] [8];
  assign _320_ = tail[1] ? _319_ : _318_;
  assign _321_ = tail[2] ? _320_ : _317_;
  assign _322_ = tail[0] ? \mem[9] [8] : \mem[8] [8];
  assign _323_ = tail[0] ? \mem[11] [8] : \mem[10] [8];
  assign _324_ = tail[1] ? _323_ : _322_;
  assign _325_ = tail[0] ? \mem[13] [8] : \mem[12] [8];
  assign _326_ = tail[0] ? \mem[15] [8] : \mem[14] [8];
  assign _327_ = tail[1] ? _326_ : _325_;
  assign _328_ = tail[2] ? _327_ : _324_;
  assign _329_ = tail[3] ? _328_ : _321_;
  assign out[8] = _329_ & ~(empty);
  assign _330_ = tail[0] ? \mem[1] [9] : \mem[0] [9];
  assign _331_ = tail[0] ? \mem[3] [9] : \mem[2] [9];
  assign _332_ = tail[1] ? _331_ : _330_;
  assign _333_ = tail[0] ? \mem[5] [9] : \mem[4] [9];
  assign _334_ = tail[0] ? \mem[7] [9] : \mem[6] [9];
  assign _335_ = tail[1] ? _334_ : _333_;
  assign _336_ = tail[2] ? _335_ : _332_;
  assign _337_ = tail[0] ? \mem[9] [9] : \mem[8] [9];
  assign _338_ = tail[0] ? \mem[11] [9] : \mem[10] [9];
  assign _339_ = tail[1] ? _338_ : _337_;
  assign _340_ = tail[0] ? \mem[13] [9] : \mem[12] [9];
  assign _341_ = tail[0] ? \mem[15] [9] : \mem[14] [9];
  assign _342_ = tail[1] ? _341_ : _340_;
  assign _343_ = tail[2] ? _342_ : _339_;
  assign _344_ = tail[3] ? _343_ : _336_;
  assign out[9] = _344_ & ~(empty);
  assign _345_ = ~(re ^ tail[0]);
  assign _001_[0] = ~(_345_ | rst);
  assign _346_ = ~tail[1];
  assign _347_ = ~(tail[1] ^ tail[0]);
  assign _348_ = re ? _347_ : _346_;
  assign _001_[1] = ~(_348_ | rst);
  assign _349_ = ~(tail[1] & tail[0]);
  assign _350_ = ~(_349_ ^ _174_);
  assign _351_ = re ? _350_ : _174_;
  assign _001_[2] = ~(_351_ | rst);
  assign _352_ = ~tail[3];
  assign _353_ = ~(_349_ | _174_);
  assign _354_ = ~(_353_ ^ tail[3]);
  assign _355_ = re ? _354_ : _352_;
  assign _001_[3] = ~(_355_ | rst);
  assign _356_ = ~(we ^ head[0]);
  assign _000_[0] = ~(_356_ | rst);
  assign _357_ = ~head[1];
  assign _358_ = we ? _171_ : _357_;
  assign _000_[1] = ~(_358_ | rst);
  assign _359_ = we ? _176_ : _178_;
  assign _000_[2] = ~(_359_ | rst);
  assign _360_ = ~head[3];
  assign _361_ = we ? _180_ : _360_;
  assign _000_[3] = ~(_361_ | rst);
  assign _362_ = _183_ | ~(_186_);
  assign _363_ = _362_ | ~(we);
  assign _002_ = _363_ ? \mem[0] [0] : in[0];
  assign _003_ = _363_ ? \mem[0] [1] : in[1];
  assign _004_ = _363_ ? \mem[0] [2] : in[2];
  assign _005_ = _363_ ? \mem[0] [3] : in[3];
  assign _006_ = _363_ ? \mem[0] [4] : in[4];
  assign _007_ = _363_ ? \mem[0] [5] : in[5];
  assign _008_ = _363_ ? \mem[0] [6] : in[6];
  assign _009_ = _363_ ? \mem[0] [7] : in[7];
  assign _010_ = _363_ ? \mem[0] [8] : in[8];
  assign _011_ = _363_ ? \mem[0] [9] : in[9];
  assign _364_ = _187_ | ~(_175_);
  assign _365_ = _364_ | ~(we);
  assign _062_ = _365_ ? \mem[15] [0] : in[0];
  assign _063_ = _365_ ? \mem[15] [1] : in[1];
  assign _064_ = _365_ ? \mem[15] [2] : in[2];
  assign _065_ = _365_ ? \mem[15] [3] : in[3];
  assign _066_ = _365_ ? \mem[15] [4] : in[4];
  assign _067_ = _365_ ? \mem[15] [5] : in[5];
  assign _068_ = _365_ ? \mem[15] [6] : in[6];
  assign _069_ = _365_ ? \mem[15] [7] : in[7];
  assign _070_ = _365_ ? \mem[15] [8] : in[8];
  assign _071_ = _365_ ? \mem[15] [9] : in[9];
  assign _366_ = _187_ | ~(_170_);
  assign _367_ = _366_ | ~(we);
  assign _052_ = _367_ ? \mem[14] [0] : in[0];
  assign _053_ = _367_ ? \mem[14] [1] : in[1];
  assign _054_ = _367_ ? \mem[14] [2] : in[2];
  assign _055_ = _367_ ? \mem[14] [3] : in[3];
  assign _056_ = _367_ ? \mem[14] [4] : in[4];
  assign _057_ = _367_ ? \mem[14] [5] : in[5];
  assign _058_ = _367_ ? \mem[14] [6] : in[6];
  assign _059_ = _367_ ? \mem[14] [7] : in[7];
  assign _060_ = _367_ ? \mem[14] [8] : in[8];
  assign _061_ = _367_ ? \mem[14] [9] : in[9];
  assign _368_ = _187_ | ~(_169_);
  assign _369_ = _368_ | ~(we);
  assign _042_ = _369_ ? \mem[13] [0] : in[0];
  assign _043_ = _369_ ? \mem[13] [1] : in[1];
  assign _044_ = _369_ ? \mem[13] [2] : in[2];
  assign _045_ = _369_ ? \mem[13] [3] : in[3];
  assign _046_ = _369_ ? \mem[13] [4] : in[4];
  assign _047_ = _369_ ? \mem[13] [5] : in[5];
  assign _048_ = _369_ ? \mem[13] [6] : in[6];
  assign _049_ = _369_ ? \mem[13] [7] : in[7];
  assign _050_ = _369_ ? \mem[13] [8] : in[8];
  assign _051_ = _369_ ? \mem[13] [9] : in[9];
  assign _370_ = _183_ | ~(_169_);
  assign _371_ = _370_ | ~(we);
  assign _072_ = _371_ ? \mem[1] [0] : in[0];
  assign _073_ = _371_ ? \mem[1] [1] : in[1];
  assign _074_ = _371_ ? \mem[1] [2] : in[2];
  assign _075_ = _371_ ? \mem[1] [3] : in[3];
  assign _076_ = _371_ ? \mem[1] [4] : in[4];
  assign _077_ = _371_ ? \mem[1] [5] : in[5];
  assign _078_ = _371_ ? \mem[1] [6] : in[6];
  assign _079_ = _371_ ? \mem[1] [7] : in[7];
  assign _080_ = _371_ ? \mem[1] [8] : in[8];
  assign _081_ = _371_ ? \mem[1] [9] : in[9];
  assign _372_ = head[2] | ~(head[3]);
  assign _373_ = _372_ | ~(_186_);
  assign _374_ = _373_ | ~(we);
  assign _142_ = _374_ ? \mem[8] [0] : in[0];
  assign _143_ = _374_ ? \mem[8] [1] : in[1];
  assign _144_ = _374_ ? \mem[8] [2] : in[2];
  assign _145_ = _374_ ? \mem[8] [3] : in[3];
  assign _146_ = _374_ ? \mem[8] [4] : in[4];
  assign _147_ = _374_ ? \mem[8] [5] : in[5];
  assign _148_ = _374_ ? \mem[8] [6] : in[6];
  assign _149_ = _374_ ? \mem[8] [7] : in[7];
  assign _150_ = _374_ ? \mem[8] [8] : in[8];
  assign _151_ = _374_ ? \mem[8] [9] : in[9];
  assign _375_ = _190_ | ~(_169_);
  assign _376_ = _375_ | ~(we);
  assign _112_ = _376_ ? \mem[5] [0] : in[0];
  assign _113_ = _376_ ? \mem[5] [1] : in[1];
  assign _114_ = _376_ ? \mem[5] [2] : in[2];
  assign _115_ = _376_ ? \mem[5] [3] : in[3];
  assign _116_ = _376_ ? \mem[5] [4] : in[4];
  assign _117_ = _376_ ? \mem[5] [5] : in[5];
  assign _118_ = _376_ ? \mem[5] [6] : in[6];
  assign _119_ = _376_ ? \mem[5] [7] : in[7];
  assign _120_ = _376_ ? \mem[5] [8] : in[8];
  assign _121_ = _376_ ? \mem[5] [9] : in[9];
  assign _377_ = _372_ | ~(_169_);
  assign _378_ = _377_ | ~(we);
  assign _152_ = _378_ ? \mem[9] [0] : in[0];
  assign _153_ = _378_ ? \mem[9] [1] : in[1];
  assign _154_ = _378_ ? \mem[9] [2] : in[2];
  assign _155_ = _378_ ? \mem[9] [3] : in[3];
  assign _156_ = _378_ ? \mem[9] [4] : in[4];
  assign _157_ = _378_ ? \mem[9] [5] : in[5];
  assign _158_ = _378_ ? \mem[9] [6] : in[6];
  assign _159_ = _378_ ? \mem[9] [7] : in[7];
  assign _160_ = _378_ ? \mem[9] [8] : in[8];
  assign _161_ = _378_ ? \mem[9] [9] : in[9];
  assign _379_ = _190_ | ~(_170_);
  assign _380_ = _379_ | ~(we);
  assign _122_ = _380_ ? \mem[6] [0] : in[0];
  assign _123_ = _380_ ? \mem[6] [1] : in[1];
  assign _124_ = _380_ ? \mem[6] [2] : in[2];
  assign _125_ = _380_ ? \mem[6] [3] : in[3];
  assign _126_ = _380_ ? \mem[6] [4] : in[4];
  assign _127_ = _380_ ? \mem[6] [5] : in[5];
  assign _128_ = _380_ ? \mem[6] [6] : in[6];
  assign _129_ = _380_ ? \mem[6] [7] : in[7];
  assign _130_ = _380_ ? \mem[6] [8] : in[8];
  assign _131_ = _380_ ? \mem[6] [9] : in[9];
  assign _381_ = _372_ | ~(_175_);
  assign _382_ = _381_ | ~(we);
  assign _022_ = _382_ ? \mem[11] [0] : in[0];
  assign _023_ = _382_ ? \mem[11] [1] : in[1];
  assign _024_ = _382_ ? \mem[11] [2] : in[2];
  assign _025_ = _382_ ? \mem[11] [3] : in[3];
  assign _026_ = _382_ ? \mem[11] [4] : in[4];
  assign _027_ = _382_ ? \mem[11] [5] : in[5];
  assign _028_ = _382_ ? \mem[11] [6] : in[6];
  assign _029_ = _382_ ? \mem[11] [7] : in[7];
  assign _030_ = _382_ ? \mem[11] [8] : in[8];
  assign _031_ = _382_ ? \mem[11] [9] : in[9];
  assign _383_ = _183_ | ~(_170_);
  assign _384_ = _383_ | ~(we);
  assign _082_ = _384_ ? \mem[2] [0] : in[0];
  assign _083_ = _384_ ? \mem[2] [1] : in[1];
  assign _084_ = _384_ ? \mem[2] [2] : in[2];
  assign _085_ = _384_ ? \mem[2] [3] : in[3];
  assign _086_ = _384_ ? \mem[2] [4] : in[4];
  assign _087_ = _384_ ? \mem[2] [5] : in[5];
  assign _088_ = _384_ ? \mem[2] [6] : in[6];
  assign _089_ = _384_ ? \mem[2] [7] : in[7];
  assign _090_ = _384_ ? \mem[2] [8] : in[8];
  assign _091_ = _384_ ? \mem[2] [9] : in[9];
  assign _385_ = _372_ | ~(_170_);
  assign _386_ = _385_ | ~(we);
  assign _012_ = _386_ ? \mem[10] [0] : in[0];
  assign _013_ = _386_ ? \mem[10] [1] : in[1];
  assign _014_ = _386_ ? \mem[10] [2] : in[2];
  assign _015_ = _386_ ? \mem[10] [3] : in[3];
  assign _016_ = _386_ ? \mem[10] [4] : in[4];
  assign _017_ = _386_ ? \mem[10] [5] : in[5];
  assign _018_ = _386_ ? \mem[10] [6] : in[6];
  assign _019_ = _386_ ? \mem[10] [7] : in[7];
  assign _020_ = _386_ ? \mem[10] [8] : in[8];
  assign _021_ = _386_ ? \mem[10] [9] : in[9];
  always @(posedge clk)
      \mem[14] [5] <= _057_;
  always @(posedge clk)
      \mem[14] [6] <= _058_;
  always @(posedge clk)
      \mem[14] [7] <= _059_;
  always @(posedge clk)
      \mem[14] [8] <= _060_;
  always @(posedge clk)
      \mem[14] [9] <= _061_;
  always @(posedge clk)
      \mem[4] [0] <= _102_;
  always @(posedge clk)
      \mem[4] [1] <= _103_;
  always @(posedge clk)
      \mem[4] [2] <= _104_;
  always @(posedge clk)
      \mem[4] [3] <= _105_;
  always @(posedge clk)
      \mem[4] [4] <= _106_;
  always @(posedge clk)
      \mem[4] [5] <= _107_;
  always @(posedge clk)
      \mem[4] [6] <= _108_;
  always @(posedge clk)
      \mem[4] [7] <= _109_;
  always @(posedge clk)
      \mem[4] [8] <= _110_;
  always @(posedge clk)
      \mem[4] [9] <= _111_;
  always @(posedge clk)
      \mem[6] [0] <= _122_;
  always @(posedge clk)
      \mem[6] [1] <= _123_;
  always @(posedge clk)
      \mem[6] [2] <= _124_;
  always @(posedge clk)
      \mem[6] [3] <= _125_;
  always @(posedge clk)
      \mem[6] [4] <= _126_;
  always @(posedge clk)
      \mem[6] [5] <= _127_;
  always @(posedge clk)
      \mem[6] [6] <= _128_;
  always @(posedge clk)
      \mem[6] [7] <= _129_;
  always @(posedge clk)
      \mem[6] [8] <= _130_;
  always @(posedge clk)
      \mem[6] [9] <= _131_;
  always @(posedge clk)
      \mem[0] [0] <= _002_;
  always @(posedge clk)
      \mem[0] [1] <= _003_;
  always @(posedge clk)
      \mem[0] [2] <= _004_;
  always @(posedge clk)
      \mem[0] [3] <= _005_;
  always @(posedge clk)
      \mem[0] [4] <= _006_;
  always @(posedge clk)
      \mem[0] [5] <= _007_;
  always @(posedge clk)
      \mem[0] [6] <= _008_;
  always @(posedge clk)
      \mem[0] [7] <= _009_;
  always @(posedge clk)
      \mem[0] [8] <= _010_;
  always @(posedge clk)
      \mem[0] [9] <= _011_;
  always @(posedge clk)
      \mem[1] [0] <= _072_;
  always @(posedge clk)
      \mem[1] [1] <= _073_;
  always @(posedge clk)
      \mem[1] [2] <= _074_;
  always @(posedge clk)
      \mem[1] [3] <= _075_;
  always @(posedge clk)
      \mem[1] [4] <= _076_;
  always @(posedge clk)
      \mem[1] [5] <= _077_;
  always @(posedge clk)
      \mem[1] [6] <= _078_;
  always @(posedge clk)
      \mem[1] [7] <= _079_;
  always @(posedge clk)
      \mem[1] [8] <= _080_;
  always @(posedge clk)
      \mem[1] [9] <= _081_;
  always @(posedge clk)
      \mem[5] [0] <= _112_;
  always @(posedge clk)
      \mem[5] [1] <= _113_;
  always @(posedge clk)
      \mem[5] [2] <= _114_;
  always @(posedge clk)
      \mem[5] [3] <= _115_;
  always @(posedge clk)
      \mem[5] [4] <= _116_;
  always @(posedge clk)
      \mem[5] [5] <= _117_;
  always @(posedge clk)
      \mem[5] [6] <= _118_;
  always @(posedge clk)
      \mem[5] [7] <= _119_;
  always @(posedge clk)
      \mem[5] [8] <= _120_;
  always @(posedge clk)
      \mem[5] [9] <= _121_;
  (* src = "fifo.v:13" *)
  always @(posedge clk)
      head[0] <= _000_[0];
  (* src = "fifo.v:13" *)
  always @(posedge clk)
      head[1] <= _000_[1];
  (* src = "fifo.v:13" *)
  always @(posedge clk)
      head[2] <= _000_[2];
  (* src = "fifo.v:13" *)
  always @(posedge clk)
      head[3] <= _000_[3];
  always @(posedge clk)
      \mem[11] [0] <= _022_;
  always @(posedge clk)
      \mem[11] [1] <= _023_;
  always @(posedge clk)
      \mem[11] [2] <= _024_;
  always @(posedge clk)
      \mem[11] [3] <= _025_;
  always @(posedge clk)
      \mem[11] [4] <= _026_;
  always @(posedge clk)
      \mem[11] [5] <= _027_;
  always @(posedge clk)
      \mem[11] [6] <= _028_;
  always @(posedge clk)
      \mem[11] [7] <= _029_;
  always @(posedge clk)
      \mem[11] [8] <= _030_;
  always @(posedge clk)
      \mem[11] [9] <= _031_;
  always @(posedge clk)
      \mem[8] [0] <= _142_;
  always @(posedge clk)
      \mem[8] [1] <= _143_;
  always @(posedge clk)
      \mem[8] [2] <= _144_;
  always @(posedge clk)
      \mem[8] [3] <= _145_;
  always @(posedge clk)
      \mem[8] [4] <= _146_;
  always @(posedge clk)
      \mem[8] [5] <= _147_;
  always @(posedge clk)
      \mem[8] [6] <= _148_;
  always @(posedge clk)
      \mem[8] [7] <= _149_;
  always @(posedge clk)
      \mem[8] [8] <= _150_;
  always @(posedge clk)
      \mem[8] [9] <= _151_;
  always @(posedge clk)
      \mem[12] [0] <= _032_;
  always @(posedge clk)
      \mem[12] [1] <= _033_;
  always @(posedge clk)
      \mem[12] [2] <= _034_;
  always @(posedge clk)
      \mem[12] [3] <= _035_;
  always @(posedge clk)
      \mem[12] [4] <= _036_;
  always @(posedge clk)
      \mem[12] [5] <= _037_;
  always @(posedge clk)
      \mem[12] [6] <= _038_;
  always @(posedge clk)
      \mem[12] [7] <= _039_;
  always @(posedge clk)
      \mem[12] [8] <= _040_;
  always @(posedge clk)
      \mem[12] [9] <= _041_;
  always @(posedge clk)
      \mem[2] [0] <= _082_;
  always @(posedge clk)
      \mem[2] [1] <= _083_;
  always @(posedge clk)
      \mem[2] [2] <= _084_;
  always @(posedge clk)
      \mem[2] [3] <= _085_;
  always @(posedge clk)
      \mem[2] [4] <= _086_;
  always @(posedge clk)
      \mem[2] [5] <= _087_;
  always @(posedge clk)
      \mem[2] [6] <= _088_;
  always @(posedge clk)
      \mem[2] [7] <= _089_;
  always @(posedge clk)
      \mem[2] [8] <= _090_;
  always @(posedge clk)
      \mem[2] [9] <= _091_;
  always @(posedge clk)
      \mem[7] [0] <= _132_;
  always @(posedge clk)
      \mem[7] [1] <= _133_;
  always @(posedge clk)
      \mem[7] [2] <= _134_;
  always @(posedge clk)
      \mem[7] [3] <= _135_;
  always @(posedge clk)
      \mem[7] [4] <= _136_;
  always @(posedge clk)
      \mem[7] [5] <= _137_;
  always @(posedge clk)
      \mem[7] [6] <= _138_;
  always @(posedge clk)
      \mem[7] [7] <= _139_;
  always @(posedge clk)
      \mem[7] [8] <= _140_;
  always @(posedge clk)
      \mem[7] [9] <= _141_;
  always @(posedge clk)
      \mem[3] [0] <= _092_;
  always @(posedge clk)
      \mem[3] [1] <= _093_;
  always @(posedge clk)
      \mem[3] [2] <= _094_;
  always @(posedge clk)
      \mem[3] [3] <= _095_;
  always @(posedge clk)
      \mem[3] [4] <= _096_;
  always @(posedge clk)
      \mem[3] [5] <= _097_;
  always @(posedge clk)
      \mem[3] [6] <= _098_;
  always @(posedge clk)
      \mem[3] [7] <= _099_;
  always @(posedge clk)
      \mem[3] [8] <= _100_;
  always @(posedge clk)
      \mem[3] [9] <= _101_;
  always @(posedge clk)
      \mem[13] [0] <= _042_;
  always @(posedge clk)
      \mem[13] [1] <= _043_;
  always @(posedge clk)
      \mem[13] [2] <= _044_;
  always @(posedge clk)
      \mem[13] [3] <= _045_;
  always @(posedge clk)
      \mem[13] [4] <= _046_;
  always @(posedge clk)
      \mem[13] [5] <= _047_;
  always @(posedge clk)
      \mem[13] [6] <= _048_;
  always @(posedge clk)
      \mem[13] [7] <= _049_;
  always @(posedge clk)
      \mem[13] [8] <= _050_;
  always @(posedge clk)
      \mem[13] [9] <= _051_;
  always @(posedge clk)
      \mem[9] [0] <= _152_;
  always @(posedge clk)
      \mem[9] [1] <= _153_;
  always @(posedge clk)
      \mem[9] [2] <= _154_;
  always @(posedge clk)
      \mem[9] [3] <= _155_;
  always @(posedge clk)
      \mem[9] [4] <= _156_;
  always @(posedge clk)
      \mem[9] [5] <= _157_;
  always @(posedge clk)
      \mem[9] [6] <= _158_;
  always @(posedge clk)
      \mem[9] [7] <= _159_;
  always @(posedge clk)
      \mem[9] [8] <= _160_;
  always @(posedge clk)
      \mem[9] [9] <= _161_;
  always @(posedge clk)
      \mem[10] [0] <= _012_;
  always @(posedge clk)
      \mem[10] [1] <= _013_;
  always @(posedge clk)
      \mem[10] [2] <= _014_;
  always @(posedge clk)
      \mem[10] [3] <= _015_;
  always @(posedge clk)
      \mem[10] [4] <= _016_;
  always @(posedge clk)
      \mem[10] [5] <= _017_;
  always @(posedge clk)
      \mem[10] [6] <= _018_;
  always @(posedge clk)
      \mem[10] [7] <= _019_;
  always @(posedge clk)
      \mem[10] [8] <= _020_;
  always @(posedge clk)
      \mem[10] [9] <= _021_;
  always @(posedge clk)
      tail[0] <= _001_[0];
  always @(posedge clk)
      tail[1] <= _001_[1];
  always @(posedge clk)
      tail[2] <= _001_[2];
  always @(posedge clk)
      tail[3] <= _001_[3];
  always @(posedge clk)
      \mem[15] [0] <= _062_;
  always @(posedge clk)
      \mem[15] [1] <= _063_;
  always @(posedge clk)
      \mem[15] [2] <= _064_;
  always @(posedge clk)
      \mem[15] [3] <= _065_;
  always @(posedge clk)
      \mem[15] [4] <= _066_;
  always @(posedge clk)
      \mem[15] [5] <= _067_;
  always @(posedge clk)
      \mem[15] [6] <= _068_;
  always @(posedge clk)
      \mem[15] [7] <= _069_;
  always @(posedge clk)
      \mem[15] [8] <= _070_;
  always @(posedge clk)
      \mem[15] [9] <= _071_;
  always @(posedge clk)
      \mem[14] [0] <= _052_;
  always @(posedge clk)
      \mem[14] [1] <= _053_;
  always @(posedge clk)
      \mem[14] [2] <= _054_;
  always @(posedge clk)
      \mem[14] [3] <= _055_;
  always @(posedge clk)
      \mem[14] [4] <= _056_;
endmodule

(* src = "ib.v:6" *)
module ib(pkti, pkto, req, ack, full, clk, rst);
  (* src = "ib.v:6" *)
  input ack;
  (* src = "ib.v:6" *)
  input clk;
  (* src = "ib.v:11" *)
  wire empty;
  (* src = "ib.v:6" *)
  output full;
  (* src = "ib.v:6" *)
  input [9:0] pkti;
  (* src = "ib.v:6" *)
  output [9:0] pkto;
  (* src = "ib.v:11" *)
  wire re;
  (* src = "ib.v:6" *)
  output [3:0] req;
  (* src = "ib.v:9" *)
  wire [3:0] reqi;
  (* src = "ib.v:6" *)
  input rst;
  (* src = "ib.v:11" *)
  wire we;
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:11" *)
  fifo fifo (
    .clk(clk),
    .empty(empty),
    .full(full),
    .in(pkti),
    .out(pkto),
    .re(re),
    .rst(rst),
    .we(we)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:14" *)
  ibsm ibsm (
    .ack(ack),
    .clk(clk),
    .empty(empty),
    .pout(pkto),
    .re(re),
    .req(req),
    .reqi(reqi),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:13" *)
  mkreq mkreq (
    .clk(clk),
    .pkti(pkto),
    .req(reqi),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:12" *)
  mkwe mkwe (
    .pkti(pkti),
    .we(we)
  );
endmodule

(* src = "ibsm.v:4" *)
module ibsm(reqi, pout, empty, ack, clk, rst, req, re);
  (* src = "ibsm.v:15" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "ibsm.v:4" *)
  input ack;
  (* src = "ibsm.v:4" *)
  input clk;
  (* src = "ibsm.v:4" *)
  input empty;
  (* src = "ibsm.v:4" *)
  input [9:0] pout;
  (* src = "ibsm.v:4" *)
  output re;
  (* src = "ibsm.v:4" *)
  output [3:0] req;
  reg [3:0] req;
  (* src = "ibsm.v:4" *)
  input [3:0] reqi;
  (* src = "ibsm.v:4" *)
  input rst;
  assign _01_ = reqi[1] | reqi[0];
  assign _02_ = reqi[3] | reqi[2];
  assign _03_ = ~(_02_ | _01_);
  assign _04_ = _03_ ? req[0] : reqi[0];
  assign _05_ = ~(pout[9] & pout[8]);
  assign _06_ = ~(_05_ & _04_);
  assign _00_[0] = ~(_06_ | rst);
  assign _07_ = _03_ ? req[1] : reqi[1];
  assign _08_ = ~(_07_ & _05_);
  assign _00_[1] = ~(_08_ | rst);
  assign _09_ = _03_ ? req[2] : reqi[2];
  assign _10_ = ~(_09_ & _05_);
  assign _00_[2] = ~(_10_ | rst);
  assign _11_ = _03_ ? req[3] : reqi[3];
  assign _12_ = ~(_11_ & _05_);
  assign _00_[3] = ~(_12_ | rst);
  (* src = "ibsm.v:15" *)
  always @(posedge clk)
      req[0] <= _00_[0];
  (* src = "ibsm.v:15" *)
  always @(posedge clk)
      req[1] <= _00_[1];
  (* src = "ibsm.v:15" *)
  always @(posedge clk)
      req[2] <= _00_[2];
  (* src = "ibsm.v:15" *)
  always @(posedge clk)
      req[3] <= _00_[3];
  assign re = 1'h0;
endmodule

(* src = "mkreq.v:4" *)
module mkreq(pkti, req, clk, rst);
  (* src = "mkreq.v:6" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "mkreq.v:4" *)
  input clk;
  (* src = "mkreq.v:4" *)
  input [9:0] pkti;
  (* src = "mkreq.v:4" *)
  output [3:0] req;
  reg [3:0] req;
  (* src = "mkreq.v:4" *)
  input rst;
  assign _01_ = pkti[1] | pkti[0];
  assign _02_ = pkti[8] | ~(pkti[9]);
  assign _03_ = pkti[9] & pkti[8];
  assign _04_ = req[0] & ~(_03_);
  assign _05_ = pkti[9] | pkti[8];
  assign _06_ = ~(_05_ & _04_);
  assign _07_ = _02_ ? _06_ : _01_;
  assign _00_[0] = ~(_07_ | rst);
  assign _08_ = pkti[1] | ~(pkti[0]);
  assign _09_ = _03_ | ~(req[1]);
  assign _10_ = _09_ | ~(_05_);
  assign _11_ = _02_ ? _10_ : _08_;
  assign _00_[1] = ~(_11_ | rst);
  assign _12_ = pkti[0] | ~(pkti[1]);
  assign _13_ = _03_ | ~(req[2]);
  assign _14_ = _13_ | ~(_05_);
  assign _15_ = _02_ ? _14_ : _12_;
  assign _00_[2] = ~(_15_ | rst);
  assign _16_ = ~(pkti[1] & pkti[0]);
  assign _17_ = _03_ | ~(req[3]);
  assign _18_ = _17_ | ~(_05_);
  assign _19_ = _02_ ? _18_ : _16_;
  assign _00_[3] = ~(_19_ | rst);
  (* src = "mkreq.v:6" *)
  always @(posedge clk)
      req[0] <= _00_[0];
  (* src = "mkreq.v:6" *)
  always @(posedge clk)
      req[1] <= _00_[1];
  (* src = "mkreq.v:6" *)
  always @(posedge clk)
      req[2] <= _00_[2];
  (* src = "mkreq.v:6" *)
  always @(posedge clk)
      req[3] <= _00_[3];
endmodule

(* src = "mkwe.v:4" *)
module mkwe(pkti, we);
  (* src = "mkwe.v:4" *)
  input [9:0] pkti;
  (* src = "mkwe.v:4" *)
  output we;
  assign we = pkti[9] | pkti[8];
endmodule

(* top =  1  *)
(* src = "sw.v:4" *)
module sw(i0, i1, i2, i3, o0, o1, o2, o3, clk, rst);
  (* src = "sw.v:7" *)
  wire ack0;
  (* src = "sw.v:11" *)
  wire ack00;
  (* src = "sw.v:12" *)
  wire ack01;
  (* src = "sw.v:13" *)
  wire ack02;
  (* src = "sw.v:14" *)
  wire ack03;
  (* src = "sw.v:8" *)
  wire ack1;
  (* src = "sw.v:11" *)
  wire ack10;
  (* src = "sw.v:12" *)
  wire ack11;
  (* src = "sw.v:13" *)
  wire ack12;
  (* src = "sw.v:14" *)
  wire ack13;
  (* src = "sw.v:9" *)
  wire ack2;
  (* src = "sw.v:11" *)
  wire ack20;
  (* src = "sw.v:12" *)
  wire ack21;
  (* src = "sw.v:13" *)
  wire ack22;
  (* src = "sw.v:14" *)
  wire ack23;
  (* src = "sw.v:10" *)
  wire ack3;
  (* src = "sw.v:11" *)
  wire ack30;
  (* src = "sw.v:12" *)
  wire ack31;
  (* src = "sw.v:13" *)
  wire ack32;
  (* src = "sw.v:14" *)
  wire ack33;
  (* src = "sw.v:4" *)
  input clk;
  (* src = "sw.v:5" *)
  wire [9:0] co0;
  (* src = "sw.v:5" *)
  wire [9:0] co1;
  (* src = "sw.v:5" *)
  wire [9:0] co2;
  (* src = "sw.v:5" *)
  wire [9:0] co3;
  (* src = "sw.v:7" *)
  (* unused_bits = "0" *)
  wire full0;
  (* src = "sw.v:8" *)
  (* unused_bits = "0" *)
  wire full1;
  (* src = "sw.v:9" *)
  (* unused_bits = "0" *)
  wire full2;
  (* src = "sw.v:10" *)
  (* unused_bits = "0" *)
  wire full3;
  (* src = "sw.v:4" *)
  input [9:0] i0;
  (* src = "sw.v:4" *)
  input [9:0] i1;
  (* src = "sw.v:4" *)
  input [9:0] i2;
  (* src = "sw.v:4" *)
  input [9:0] i3;
  (* src = "sw.v:4" *)
  output [9:0] o0;
  (* src = "sw.v:4" *)
  output [9:0] o1;
  (* src = "sw.v:4" *)
  output [9:0] o2;
  (* src = "sw.v:4" *)
  output [9:0] o3;
  (* src = "sw.v:6" *)
  wire [3:0] req0;
  (* src = "sw.v:6" *)
  wire [3:0] req1;
  (* src = "sw.v:6" *)
  wire [3:0] req2;
  (* src = "sw.v:6" *)
  wire [3:0] req3;
  (* src = "sw.v:4" *)
  input rst;
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:11" *)
  ackor ackor0 (
    .ack(ack0),
    .ack0x(ack00),
    .ack1x(ack10),
    .ack2x(ack20),
    .ack3x(ack30)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:12" *)
  ackor ackor1 (
    .ack(ack1),
    .ack0x(ack01),
    .ack1x(ack11),
    .ack2x(ack21),
    .ack3x(ack31)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:13" *)
  ackor ackor2 (
    .ack(ack2),
    .ack0x(ack02),
    .ack1x(ack12),
    .ack2x(ack22),
    .ack3x(ack32)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:14" *)
  ackor ackor3 (
    .ack(ack3),
    .ack0x(ack03),
    .ack1x(ack13),
    .ack2x(ack23),
    .ack3x(ack33)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:15" *)
  arb arb0 (
    .ackx0(ack00),
    .ackx1(ack01),
    .ackx2(ack02),
    .ackx3(ack03),
    .clk(clk),
    .req0(req0[0]),
    .req1(req1[0]),
    .req2(req2[0]),
    .req3(req3[0]),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:16" *)
  arb arb1 (
    .ackx0(ack10),
    .ackx1(ack11),
    .ackx2(ack12),
    .ackx3(ack13),
    .clk(clk),
    .req0(req0[1]),
    .req1(req1[1]),
    .req2(req2[1]),
    .req3(req3[1]),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:17" *)
  arb arb2 (
    .ackx0(ack20),
    .ackx1(ack21),
    .ackx2(ack22),
    .ackx3(ack23),
    .clk(clk),
    .req0(req0[2]),
    .req1(req1[2]),
    .req2(req2[2]),
    .req3(req3[2]),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:18" *)
  arb arb3 (
    .ackx0(ack30),
    .ackx1(ack31),
    .ackx2(ack32),
    .ackx3(ack33),
    .clk(clk),
    .req0(req0[3]),
    .req1(req1[3]),
    .req2(req2[3]),
    .req3(req3[3]),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:19" *)
  cb cb (
    .d0({ ack03, ack02, ack01, ack00 }),
    .d1({ ack13, ack12, ack11, ack10 }),
    .d2({ ack23, ack22, ack21, ack20 }),
    .d3({ ack33, ack32, ack31, ack30 }),
    .i0(co0),
    .i1(co1),
    .i2(co2),
    .i3(co3),
    .o0(o0),
    .o1(o1),
    .o2(o2),
    .o3(o3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:7" *)
  ib ib0 (
    .ack(ack0),
    .clk(clk),
    .full(full0),
    .pkti(i0),
    .pkto(co0),
    .req(req0),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:8" *)
  ib ib1 (
    .ack(ack1),
    .clk(clk),
    .full(full1),
    .pkti(i1),
    .pkto(co1),
    .req(req1),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:9" *)
  ib ib2 (
    .ack(ack2),
    .clk(clk),
    .full(full2),
    .pkti(i2),
    .pkto(co2),
    .req(req2),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:10" *)
  ib ib3 (
    .ack(ack3),
    .clk(clk),
    .full(full3),
    .pkti(i3),
    .pkto(co3),
    .req(req3),
    .rst(rst)
  );
endmodule
